### ISSUE TITLE
Strict-mode awkwardness

### ISSUE THREAD

**Issue by NullVoxPopuli** [tracked-tools/ember-async-data#352]
In strict-mode, all things need to be imported, but, the easiest `load` import, requires a destroyable as the second param.
```ts
import { load } from 'ember-async-data';
```

But this is not a helper, ref: https://github.com/chriskrycho/ember-async-data/blob/main/addon/helpers/load.ts#L66-L77

the helper would have to be imported as
```ts
import load from 'ember-async-data/helpers/load';
```

Could it be possible to overload the top-level `load` function to work in both scenarios?

**Comment by chriskrycho** [comment]
Thanks for the report. It *is* actually a helper, courtesy of someone's :wink: work on making the default helper manager work, but you’re correct that it isn't a class-based helper. And the reason it has the API it doses so that when you use it in a normal JS context, you don’t leak promise state across your tests. I'm not sure that's a *problem*? It’s *annoying*, but that’s JS. Using it with the class-based helper would be even *more* annoying, since that would involve `invokeHelper(Load, () => this.somePromise)`, which is muuuuuuch worse than `load(this.somePromise, this)` in my opinion. 🤔

**Comment by NullVoxPopuli** [comment]
> but you’re correct that it isn't a class-based helper

not just that, but in template-only `<template>` contexts, it's impossible to use as there is no destroyable to pass, and the assert throws an error :see_no_evil: 

> since that would involve invokeHelper(Load, () => this.somePromise)

A resource could automatically wire this up, if that's of interest

All of these are equivelent, using the same definition
1. with `@use`
```js
class extends Component {
  @use state = load(() => this.someAsyncCall()); 
}
```
2. without `@use`
```js
class extends Component {
   state = load(this, () => this.someAsyncCall()); 
}
```
3. in a template
```hbs
{{#let (load (this.someAsyncCall)) as |state|}}

{{/let}}
```

**Comment by chriskrycho** [comment]
I think a resource is probably the best way to model that, and notably comes with the same restriction of needing to pass `this` in one way or another. I'm slightly iffy on shipping a resource here until we finalize that API, though. Notably, the second example you give—

```js
class extends Component {
   state = load(this, () => this.someAsyncCall()); 
}
```

—looks an awful lot like what you’d do with the existing API, just changing which order the `this` goes in and where/how you set up the async.

```js
class extends Component {
   @cached get state() {
     return load(this.someAsyncCall(), this);
   }
}
```

Notably, you *can* use class-based helpers in `<template>` contexts, even if it feels a bit… odd… syntactically:

```js
import Load from 'tracked-async-data/helpers/load';

<template>
  {{#let (Load (this.someAsyncCall)) as |state|}}
    {{! ... }}
  {{/let}}
</template>
```

**Comment by chriskrycho** [comment]
Yep, and as soon as we have a stable design for resources, I think we should absolutely adopt that here!

**Comment by NullVoxPopuli** [comment]
What does it take to declare a design stable? RFC + asking people to try the library? It def needs more feedback on use cases of timing behaviors, etc.

**Comment by chriskrycho** [comment]
Yeah, those are what I'd want to see before shipping that as a first-class thing here, because this has been out and stable for quite a while, and it’s used *extensively* at LinkedIn in ways that would make me leery of having a period of churn/instability around the library itself.

That said, a library which *wraps* this would be super welcome. Alternatively, we could think about shipping it here, but with that feature explicitly as being in beta and unstable and therefore warning folks that they’re signing up for the possibility of churn if they adopt. (A separate library seems… better?)

**Comment by chriskrycho** [comment]
This is now mostly irrelevant since `v0.5.2`/`v0.6.1`/`v0.7.1`/`v1.0.1` removed the need for the destroyable (we were just trolling ourselves with it). 🎉

**Comment by NullVoxPopuli** [comment]
yay!!
